name: Test MLTT Schedule

on:
  workflow_dispatch:  # Permet de lancer manuellement le workflow

jobs:    
  test-mltt:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.x"

      - name: Install dependencies
        run: pip install requests beautifulsoup4 icalendar
  
      - name: Run MLTT probe script
        run: python test_mltt_structure.py
