
name: Test MLTT Script

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  run_script:
    runs-on: ubuntu-latest

    steps:
      # Récupération du code
      - uses: actions/checkout@v3

      # Installation de Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      # Installation des dépendances
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # Exécution du script Python
      - name: Run MLTT script
        run: python test_mltt_structure.py
